# Generated by Django 4.0.1 on 2022-02-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReestrTSZH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=150, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=150, verbose_name='Отчество')),
                ('date', models.DateField(verbose_name='Дата вступления')),
                ('address', models.CharField(max_length=150, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name_plural': 'Реестр ТСЖ',
            },
        ),
        migrations.AlterModelOptions(
            name='protocols',
            options={'verbose_name_plural': 'Протоколы'},
        ),
    ]
