# Generated by Django 4.0.1 on 2022-02-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reestrtszh_alter_protocols_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reestrtszh',
            name='number',
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='statements/%Y/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reestrtszh')),
            ],
        ),
    ]
